<?php

/**
 * @file
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function klaviyo_form_user_admin_settings_alter(&$form, $form_state) {
  $klaviyo = Klaviyo::getInstance();

  if ($klaviyo->isCompatiableEntity('user')) {
    $default_values = $klaviyo->getAllEntitySettings('user');

    $form['klaviyo'] = array(
     '#type' => 'fieldset',
     '#title' => t('Klaviyo'),
     '#tree' => TRUE,
    );
    $form['klaviyo']['enabled'] = array(
      '#type' => 'checkbox',
      '#title' => t('Enable'),
      '#default_value' => $default_values['enabled'],
      '#description' => t('Enable Klaviyo mapping for user accounts.'),
    );
    $form['klaviyo']['settings'] = array(
      '#type' => 'container',
      '#attributes' => array(
        'class' => array('klaviyo-settings')
      ),
      '#states' => array(
        'visible' => array(
          ':input[name="klaviyo[enabled]"]' => array('checked' => TRUE)
        ),
      ),
    );
    $form['klaviyo']['settings']['list'] = array(
      '#type' => 'select_or_other',
      '#title' => t('List/Segment'),
      '#other' => t('Create a new list'),
      '#default_value' => $default_values['settings']['list'],
      '#options' => array(
        '_none' => t('Not used'),
      ) + $klaviyo->getCachedListOptions(),
      '#description' => t("Select a list to add all Drupal user accounts. This is used for looking up users so that if a user's email address is changed then we can update the user's Klaviyo person record. <br /> Note: If you select a segment then users will not be added as segments are dynamically generated lists."),
    );

    $form['#submit'][] = 'klaviyo_form_user_admin_settings_alter_validate';
    $form['#submit'][] = 'klaviyo_form_user_admin_settings_alter_submit';
  }
}

function klaviyo_form_user_admin_settings_alter_validate(&$form, $form_state) {
  // @todo: 'Some validation...'
}

function klaviyo_form_user_admin_settings_alter_submit(&$form, $form_state) {
  $values = $form_state['values'];

  if (!empty($values['klaviyo'])) {
    if (!empty($values['klaviyo']['settings']['list']) && $list_id_full = $values['klaviyo']['settings']['list']) {
      $klaviyo = Klaviyo::getInstance();

      list(, $list_id) = $klaviyo->parseFullListId($list_id_full);
      if (empty($list_id)) {
        $list = $klaviyo->api->createList($list_id_full);
        $values['klaviyo']['settings']['list'] = $klaviyo->createFullListId($list);
      }
    }

    variable_set('klaviyo_entity_settings_user', $values['klaviyo']);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function klaviyo_form_field_ui_field_edit_form_alter(&$form, $form_state, $form_id) {
  $klaviyo = Klaviyo::getInstance();
  $entity_type = !empty($form['instance']['entity_type']['#value']) ? $form['instance']['entity_type']['#value'] : '';
  if ($klaviyo->isFieldMappable($entity_type, $form['#field']['type'])) {
    $form['klaviyo'] = array(
     '#type' => 'fieldset',
     '#title' => t('Klaviyo'),
     '#tree' => TRUE,
    );

    $attributes = variable_get('klaviyo_person_attributes_user', array());
    $default_value = !empty($attributes[$form['#field']['field_name']]) ? $attributes[$form['#field']['field_name']] : '_none';
    $form['klaviyo']['person_attribute'] = array(
      '#type' => 'select_or_other',
      '#title' => t('Attribute'),
      '#other' => t('Custom'),
      '#default_value' => $default_value,
      '#options' => array(
        '_none' => t('Not used'),
      ) + $klaviyo->getPersonMappableAttributeOptions('user', $form['#field']['field_name']),
      '#description' => t('Select the attribute for which this field should map in Klaviyo, if any.'),
    );

    $form['#validate'][] = 'klaviyo_form_field_ui_field_edit_form_validate';
    $form['#submit'][] = 'klaviyo_form_field_ui_field_edit_form_submit';
  }
}

function klaviyo_form_field_ui_field_edit_form_validate(&$form, &$form_state) {
  $values = $form_state['values'];

  if (!empty($values['klaviyo']['person_attribute']) && $attribute_key = $values['klaviyo']['person_attribute']) {
    // @todo: Check that it is not already used.
    // @todo: Check that it is a clean string < 125 chars (or max variable size?).
  }
}

function klaviyo_form_field_ui_field_edit_form_submit(&$form, &$form_state) {
  $values = $form_state['values'];

  if (!empty($values['klaviyo']['person_attribute']) && $attribute_key = $values['klaviyo']['person_attribute']) {
    $attributes = variable_get('klaviyo_person_attributes_user', array());
    if ($attribute_key === '_none' && !empty($attributes[$form['#field']['field_name']])) {
      unset($attributes[$form['#field']['field_name']]);
    }
    else {
      $attributes[$form['#field']['field_name']] = $attribute_key;
    }
    variable_set('klaviyo_person_attributes_user', $attributes);
  }
}

/**
 * Implements hook_user_presave().
 */
function klaviyo_user_presave(&$edit, $account, $category) {
  $klaviyo = Klaviyo::getInstance();

  if (!$klaviyo->isEnabledOnEntity('user')) {
    return;
  }

  // We do this in presave so that we can add our Klaviyo information to the
  // generic user data storage.
  if ($account->is_new) {
    // @todo: Find a better way to handle this. Really leaning toward creating
    //        our own table;
    $edit['data']['klaviyo'] = array('one_time_lookup' => TRUE);
  }
  elseif (empty($account->klaviyo['id']) && $settings = $klaviyo->getAllEntitySettings('user')) {
    if (!empty($settings['settings']['list']) && $list_id_full = $settings['settings']['list']) {
      $mail = (!empty($edit['original'])) ? $edit['original']->mail : $account->mail;
      list(, $list_id) = $klaviyo->parseFullListId($list_id_full);
      if ($person_list = $klaviyo->api->lookUpPersonFromList($list_id, $mail)) {
        $edit['data']['klaviyo'] = array('id' => $person_list->person->id);
      }
    }
  }
}

/**
 * Implements hook_user_insert().
 */
function klaviyo_user_insert(&$edit, $account, $category) {
  Klaviyo::getInstance()->saveEntity('user', $account, $edit);
}

/**
 * Implements hook_user_update().
 */
function klaviyo_user_update(&$edit, $account, $category) {
  Klaviyo::getInstance()->saveEntity('user', $account, $edit);
}
