<?php

/**
 * @file
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function klaviyo_form_field_ui_field_edit_form_alter(&$form, $form_state, $form_id) {
  $is_user_entity = (!empty($form['instance']['entity_type']['#value']) && $form['instance']['entity_type']['#value'] === 'user');

  if ($is_user_entity && $form['#field']['type'] === 'text') {
    $form['klaviyo'] = array(
     '#type' => 'fieldset',
     '#title' => t('Klaviyo'),
    );
    $form['klaviyo']['person_attribute'] = array(
      '#type' => 'select_or_other',
      '#options' => array(
        '_none' => t('Not used'),
      ),
      '#description' => t('Select the attribute for which this field should map in Klaviyo, if any.'),
    );
  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
/*
function klaviyo_field_widget_form_alter(&$element, &$form_state, &$context) {
  if ($context['instance']['entity_type'] === 'user') {
    dpm($context);
  }
}
*/
